apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres:13.1
        env:
        - name: POSTGRES_PASSWORD
          value: Passw)rd2024!
        - name: POSTGRES_USER
          value: reviewfilmes
        - name: POSTGRES_DB
          value: reviewfilmes
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
  - port: 5432