name: CI-CD Argo
on:
  push:
    branches: ["main"]
    paths-ignore:
      - k8s/*
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código fonte
        uses: actions/checkout@v4.1.7

      - name: Login to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.3.0
        with:
          context: ./src
          push: true
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: |
            jancunha/review-filmes:v${{ github.run_number }}
            jancunha/review-filmes:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Checkout do código fonte
        uses: actions/checkout@v4.1.7
      
      - name: GitOps - Patch and Push
        run: |
          git config --global user.name "João Alberto"
          git config --global user.email "jancunha@gmail.com"
          sed -i 's/image: jancunha\/review-filmes:v[0-9]\{1,3\}/image: jancunha\/review-filmes:v${{github.run_number}}/' ./k8s/deployment.yaml
          git add ./k8s
          git commit -m "Alteração para a imagem jancunha/review-filmes:v${{ github.run_number }}"
          git push origin