name: CI-CD-AWS
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código fonte
        uses: actions/checkout@v4.1.7

      - name: Login to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.3.0
        with:
          context: ./src
          push: true
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: |
            jancunha/review-filmes:v${{ github.run_number }}
            jancunha/review-filmes:latest
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Config AWS CLI
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Config Kubeconfig
        run: aws eks update-kubeconfig --name k8slab

      - name: Deploy Kubernetes
        uses: Azure/k8s-deploy@v5
        with:
            manifests: |
              ./k8s/deployment.yaml
            images: |
              'jancunha/review-filmes:v${{ github.run_number }}'
